import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import path from "path";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    // ── Dev-server security headers ───────────────────────────────────────
    // These are served during `vite dev`. The equivalent production
    // headers live in vercel.json, netlify.toml, and public/_headers
    // (all generated by this build config) so they are enforced by the
    // CDN/hosting layer regardless of which platform you deploy to.
    {
      name: "security-headers",
      configureServer(server) {
        server.middlewares.use((_req, res, next) => {
          res.setHeader("X-Content-Type-Options", "nosniff");
          res.setHeader("X-Frame-Options", "DENY");
          res.setHeader("X-XSS-Protection", "1; mode=block");
          res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
          res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
          // A permissive-but-real CSP for IPTV: we need to allow media
          // from any origin (stream CDNs we don't control), external
          // images for channel logos, Firebase, and geojs.io (IP geo).
          // We deliberately do NOT include 'unsafe-eval' — HLS.js and
          // mpegts.js work without it in modern bundler mode.
          res.setHeader(
            "Content-Security-Policy",
            [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline'",        // inline needed by Vite HMR in dev
              "style-src 'self' 'unsafe-inline'",
              "media-src *",                               // IPTV streams from any CDN
              "img-src * data: blob:",                     // channel logos from any origin
              "connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://*.firebaseapp.com https://get.geojs.io wss://*.firebaseio.com https://raw.githubusercontent.com",
              "frame-ancestors 'none'",
            ].join("; ")
          );
          next();
        });
      },
    },
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: ["favicon.svg", "apple-touch-icon.png"],
      manifest: {
        name: "Shahriar TV - Premium IPTV Streaming",
        short_name: "Shahriar TV",
        description: "Your Family Entertainment Hub - Premium IPTV streaming platform",
        theme_color: "#0a0a0d",
        background_color: "#050507",
        display: "standalone",
        orientation: "any",
        start_url: "/",
        scope: "/",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
          { src: "/icons/icon-maskable-192.png", sizes: "192x192", type: "image/png", purpose: "maskable" },
          { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      workbox: {
        globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"],
        navigateFallbackDenylist: [/^\/api/],
        navigateFallback: "/index.html",
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.endsWith(".m3u") || url.pathname.endsWith(".m3u8"),
            handler: "NetworkFirst",
            options: {
              cacheName: "playlist-cache",
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 6 },
              networkTimeoutSeconds: 10,
            },
          },
          {
            urlPattern: ({ url, request }) =>
              url.pathname.endsWith(".json") && request.destination !== "document",
            handler: "NetworkFirst",
            options: {
              cacheName: "json-playlist-cache",
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 6 },
              networkTimeoutSeconds: 10,
            },
          },
          {
            urlPattern: ({ request }) => request.destination === "image",
            handler: "CacheFirst",
            options: {
              cacheName: "image-cache",
              expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 7 },
            },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    // ── Aggressive chunk splitting ─────────────────────────────────────────
    // Goal: keep the eagerly-loaded initial chunks (index.js + its static
    // imports) as small as possible so users see the UI fast on any network.
    // All player engines (hls.js, shaka, mpegts.js), Firebase, and
    // Zustand/TanStack are moved to on-demand chunks split either here or
    // by the dynamic `import()` calls in the source.
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          if (!id.includes("node_modules")) return;

          // ── React ecosystem — always eagerly needed ───────────────────
          if (
            id.includes("/react/") ||
            id.includes("/react-dom/") ||
            id.includes("/react-router")
          ) return "vendor-react";

          // ── Firebase — lazy at runtime, but large enough to isolate ──
          if (id.includes("firebase")) return "vendor-firebase";

          // ── State / data-fetching — small but used on every page ─────
          if (
            id.includes("zustand") ||
            id.includes("@tanstack")
          ) return "vendor-state";

          // ── Animation ────────────────────────────────────────────────
          if (id.includes("framer-motion")) return "vendor-motion";

          // ── Player engines — lazy via dynamic import() in code ────────
          // These are already code-split by the dynamic import() calls in
          // useHlsPlayer.ts, but naming them here means Vite will give
          // them stable, human-readable chunk names in the dist directory.
          if (id.includes("hls.js")) return "vendor-hls";
          if (id.includes("shaka-player")) return "vendor-shaka";
          if (id.includes("mpegts")) return "vendor-mpegts";

          // ── Misc utilities ────────────────────────────────────────────
          if (id.includes("idb")) return "vendor-idb";
          if (id.includes("fuse")) return "vendor-fuse";
          if (id.includes("lucide")) return "vendor-icons";
        },
      },
    },
  },
});
